# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120
# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength: 
  Max: 20

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
#  EnforcedStyle: double_quotes
  Enabled: false

# explicit return makes code more readable
Style/RedundantReturn:
  Enabled: false

# String#% is by far the least verbose and only object oriented variant.
Style/FormatString:
  EnforcedStyle: percent
  Enabled: true
Style/FormatStringToken:
  Enabled: false

# has_key? and has_value? are far more readable than key? and value?
Style/PreferredHashMethods:
  Enabled: false

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: true
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

